"""Signal models."""

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel


class SignalType(StrEnum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class Signal(BaseModel):
    """A trading signal generated by a strategy."""

    ticker: str
    signal_type: SignalType
    strategy_name: str
    score: float  # Higher = stronger conviction
    rationale: str
    generated_at: datetime
    price_at_signal: float | None = None
    target_price: float | None = None
    stop_loss: float | None = None
